---
title: "Explore data"
author: "Jolyon Faria"
date: "25/10/2020"
output: html_notebook
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, include = FALSE, warning = FALSE)

```

```{r}

# Packages
library(awatchr)
library(here)
library(magrittr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(pander)
library(xml2)

# Config
stopifnot(file.exists(here(watch_export_file)))

```

```{r}

# Get data
records <- read_xml(watch_export_file) %>%
  xml_children

```

```{r, include=TRUE}

# Get record types
record_types <- xml_attr(records, "type")
record_types %>%
  table(dnn="Record_type") %>%
  as.data.frame %>%
  arrange(desc(Freq)) %>%
  mutate(Count = prettyNum(Freq, big.mark=",")) %>%
  select(-Freq) %>%
  pander

```

```{r, include = TRUE}

heart_rate_records <- records[which(record_types == "HKQuantityTypeIdentifierHeartRate")]

heart_rate_df <- data_frame(
  date = as.POSIXct(xml_attr(heart_rate_records, "endDate")),
  heart_rate = as.integer(xml_attr(heart_rate_records, "value"))
)
head(heart_rate_df)
saveRDS(heart_rate_df, file = heart_rate_file)

```

\newpage

# Appendix

```{r}

sessionInfo()

```
